package com.memento.practice.api;

public class Champion {
    //attributes
    private Integer id;
    private String name;
    private Boolean ranged;
    private Boolean melee;
    private String damageType;

    //deefault construstor 
    public Champion() {
    }

    public Champion( Integer id, String name, Boolean ranged, Boolean melee, String damageType) {
        this.id = id;
        this.name = name;
        this.ranged = ranged;
        this.melee = melee;
        this.damageType = damageType;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean isRanged() {
        return this.ranged;
    }

    public Boolean getRanged() {
        return this.ranged;
    }

    public void setRanged(Boolean ranged) {
        this.ranged = ranged;
    }

    public Boolean isMelee() {
        return this.melee;
    }

    public Boolean getMelee() {
        return this.melee;
    }

    public void setMelee(Boolean melee) {
        this.melee = melee;
    }

    public String getDamageType() {
        return this.damageType;
    }

    public void setDamageType(String damageType) {
        this.damageType = damageType;
    }

    //generated by vscode
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((ranged == null) ? 0 : ranged.hashCode());
        result = prime * result + ((melee == null) ? 0 : melee.hashCode());
        result = prime * result + ((damageType == null) ? 0 : damageType.hashCode());
        return result;
    }

    //generated by vscode
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Champion other = (Champion) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        if (ranged == null) {
            if (other.ranged != null)
                return false;
        } else if (!ranged.equals(other.ranged))
            return false;
        if (melee == null) {
            if (other.melee != null)
                return false;
        } else if (!melee.equals(other.melee))
            return false;
        if (damageType == null) {
            if (other.damageType != null)
                return false;
        } else if (!damageType.equals(other.damageType))
            return false;
        return true;
    }

    


}